service: serverless-bootstrap

frameworkVersion: "3"

org: null
app: null

useDotenv: true

custom:
  profiles:
    dev: convergix
    prod: convergix
  # doraEventBusName: ${self:service}-${sls:stage}-dora-bus-${aws:accountId}
  doraEventBusName: event-bus-serverless-bootstrap-dora-metrics

provider:
  name: aws
  # profile: ${self:custom.profiles.${sls:stage}}
  runtime: nodejs18.x
  region: ap-southeast-2

  logs:
    httpApi:
      format: '{"requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "routeKey":"$context.routeKey", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength"}'

  httpApi:
    cors:
      allowedOrigins: ${env:APP_BASE_URL}
      allowedHeaders:
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - OPTIONS

  environment:
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DORA_METRICS_NAMESPACE: "${self:service}/DORA"
    ENVIRONMENT: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "cloudwatch:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "*"

functions:
  dealFind:
    handler: src/functions/deal/dealFind.handler
    events:
      - httpApi:
          path: /deal/find
          method: get

  dealSave:
    handler: src/functions/deal/dealSave.handler
    events:
      - httpApi:
          path: /deal/save
          method: post

  deploymentFrequency:
    handler: src/dora/deploymentFrequency.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.doraEventBusName}
          pattern:
            detail-type:
              - DeploymentSuccess

  leadTimeForChanges:
    handler: src/dora/leadTimeForChanges.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.doraEventBusName}
          pattern:
            detail-type:
              - DeploymentSuccess

  changeFailureRate:
    handler: src/dora/changeFailureRate.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.doraEventBusName}
          pattern:
            detail-type:
              - DeploymentFailure

  mttr:
    handler: src/dora/mttr.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.doraEventBusName}
          pattern:
            detail-type:
              - IncidentResolved

resources:
  Resources:
    DoraEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.doraEventBusName}

    DORAMetricsDashboard:
      Type: AWS::CloudWatch::Dashboard
      Properties:
        DashboardName: DORA_Metrics
        DashboardBody: |
          {
            "widgets": [
              {
                "type": "text",
                "x": 0,
                "y": 0,
                "width": 24,
                "height": 1,
                "properties": {
                  "markdown": "### Dashboard for DORA Metrics"
                }
              },
              {
                "type": "metric",
                "x": 0,
                "y": 1,
                "width": 6,
                "height": 6,
                "properties": {
                  "metrics": [["Custom/DORA", "DeploymentFrequency"]],
                  "view": "singleValue"
                }
              },
              {
                "type": "metric",
                "x": 6,
                "y": 1,
                "width": 6,
                "height": 6,
                "properties": {
                  "metrics": [["Custom/DORA", "LeadTimeForChanges"]],
                  "view": "singleValue"
                }
              },
              {
                "type": "metric",
                "x": 12,
                "y": 1,
                "width": 6,
                "height": 6,
                "properties": {
                  "metrics": [["Custom/DORA", "ChangeFailureRate"]],
                  "view": "singleValue"
                }
              },
              {
                "type": "metric",
                "x": 18,
                "y": 1,
                "width": 6,
                "height": 6,
                "properties": {
                  "metrics": [["Custom/DORA", "MTTR"]],
                  "view": "singleValue"
                }
              }
            ]
          }
