service: serverless-bootstrap

frameworkVersion: "3"

org: null
app: null

useDotenv: true

custom:
  profiles:
    dev: convergix
    prod: convergix
  doraEventBusName: ${self:service}-${sls:stage}-dora-bus-${aws:accountId}

provider:
  name: aws
  # profile: ${self:custom.profiles.${sls:stage}}
  runtime: nodejs18.x
  region: ap-southeast-2

  logs:
    httpApi:
      format: '{"requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "routeKey":"$context.routeKey", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength"}'

  httpApi:
    cors:
      allowedOrigins: ${env:APP_BASE_URL}
      allowedHeaders:
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - OPTIONS

  environment:
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DORA_METRICS_NAMESPACE: "${self:service}/DORA"
    ENVIRONMENT: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "cloudwatch:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "*"

functions:
  dealFind:
    handler: src/functions/deal/dealFind.handler
    events:
      - httpApi:
          path: /deal/find
          method: get

  dealSave:
    handler: src/functions/deal/dealSave.handler
    events:
      - httpApi:
          path: /deal/save
          method: post

  doraMetrics:
    handler: src/functions/dora/metrics.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.doraEventBusName}
          pattern:
            source:
              - serverless-app
            detail-type:
              - deployment_start
              - deployment_success
              - deployment_failure
              - incident_start
              - incident_resolve
    environment:
      DORA_METRICS_NAMESPACE: "${self:service}/DORA"
      ENVIRONMENT: ${sls:stage}

resources:
  Resources:
    DoraDashboard:
      Type: AWS::CloudWatch::Dashboard
      Properties:
        DashboardName: ${self:service}-${sls:stage}-dora-metrics
        DashboardBody: !Sub |
          {
            "widgets": [
              {
                "type": "text",
                "width": 24,
                "height": 1,
                "properties": {
                  "markdown": "# Dashboard for DORA Metrics Per Day"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "MTTR", "Environment", "prod", {
                      "label": "MTTR Per Day",
                      "stat": "Average",
                      "period": 86400
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "MTTR Per Day",
                  "period": 86400
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ { "expression": "(m2 / m1) * 100", "label": "Change Failure Rate (%)" } ],
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", { "id": "m1", "stat": "Sum", "visible": false, "period": 86400 } ],
                    [ ".", "DeploymentFailures", "Environment", "prod", { "id": "m2", "stat": "Sum", "visible": false, "period": 86400 } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Change Failure Rate Per Day",
                  "period": 86400
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", {
                      "label": "Deployments Per Day",
                      "stat": "Sum",
                      "period": 86400
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Deployment Frequency Per Day",
                  "period": 86400
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "LeadTimeForChanges", "Environment", "prod", {
                      "label": "Lead Time Per Day (Minutes)",
                      "stat": "Average",
                      "period": 86400
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Lead Time for Change Per Day",
                  "period": 86400
                }
              },
              {
                "type": "text",
                "width": 24,
                "height": 1,
                "properties": {
                  "markdown": "# Dashboard for DORA Metrics Per Week"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "MTTR", "Environment", "prod", {
                      "label": "MTTR Per Week",
                      "stat": "Average",
                      "period": 604800
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "MTTR Per Week"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ { "expression": "(m2 / m1) * 100", "label": "Change Failure Rate (%)" } ],
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", { "id": "m1", "stat": "Sum", "visible": false, "period": 604800 } ],
                    [ ".", "DeploymentFailures", "Environment", "prod", { "id": "m2", "stat": "Sum", "visible": false, "period": 604800 } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Change Failure Rate Per Week"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", {
                      "label": "Deployments Per Week",
                      "stat": "Sum",
                      "period": 604800
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Deployment Frequency Per Week"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "LeadTimeForChanges", "Environment", "prod", {
                      "label": "Lead Time Per Week (Minutes)",
                      "stat": "Average",
                      "period": 604800
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Lead Time for Change Per Week"
                }
              },
              {
                "type": "text",
                "width": 24,
                "height": 1,
                "properties": {
                  "markdown": "# Dashboard for DORA Metrics Per Month"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "MTTR", "Environment", "prod", {
                      "label": "MTTR Per Month",
                      "stat": "Average",
                      "period": 2592000
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "MTTR Per Month"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ { "expression": "(m2 / m1) * 100", "label": "Change Failure Rate (%)" } ],
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", { "id": "m1", "stat": "Sum", "visible": false, "period": 2592000 } ],
                    [ ".", "DeploymentFailures", "Environment", "prod", { "id": "m2", "stat": "Sum", "visible": false, "period": 2592000 } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Change Failure Rate Per Month"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", {
                      "label": "Deployments Per Month",
                      "stat": "Sum",
                      "period": 2592000
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Deployment Frequency Per Month"
                }
              },
              {
                "type": "metric",
                "width": 6,
                "height": 6,
                "properties": {
                  "view": "singleValue",
                  "metrics": [
                    [ "${self:service}/DORA", "LeadTimeForChanges", "Environment", "prod", {
                      "label": "Lead Time Per Month (Minutes)",
                      "stat": "Average",
                      "period": 2592000
                    } ]
                  ],
                  "region": "${AWS::Region}",
                  "setPeriodToTimeRange": false,
                  "title": "Lead Time for Change Per Month"
                }
              }
            ]
          }
