service: serverless-bootstrap

frameworkVersion: "3"

org: null
app: null

useDotenv: true

custom:
  profiles:
    dev: convergix
    prod: convergix
  doraEventBusName: ${self:service}-${sls:stage}-dora-bus-${aws:accountId}

provider:
  name: aws
  # profile: ${self:custom.profiles.${sls:stage}}
  runtime: nodejs18.x
  region: ap-southeast-2

  logs:
    httpApi:
      format: '{"requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "routeKey":"$context.routeKey", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength"}'

  httpApi:
    cors:
      allowedOrigins: ${env:APP_BASE_URL}
      allowedHeaders:
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - OPTIONS

  environment:
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DORA_METRICS_NAMESPACE: "${self:service}/DORA"
    ENVIRONMENT: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "cloudwatch:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "*"

functions:
  dealFind:
    handler: src/functions/deal/dealFind.handler
    events:
      - httpApi:
          path: /deal/find
          method: get

  dealSave:
    handler: src/functions/deal/dealSave.handler
    events:
      - httpApi:
          path: /deal/save
          method: post

  doraMetrics:
    handler: src/functions/dora/metrics.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.doraEventBusName}
          pattern:
            source:
              - serverless-app
            detail-type:
              - deployment_start
              - deployment_success
              - deployment_failure
              - incident_start
              - incident_resolve
    environment:
      DORA_METRICS_NAMESPACE: "${self:service}/DORA"
      ENVIRONMENT: ${sls:stage}

resources:
  Resources:
    DoraDashboard:
      Type: AWS::CloudWatch::Dashboard
      Properties:
        DashboardName: dashboard-${self:service}-${sls:stage}-dora-metrics
        DashboardBody: !Sub |
          {
            "widgets": [
              {
                "type": "metric",
                "width": 12,
                "height": 6,
                "properties": {
                  "metrics": [
                    [ "${self:service}/DORA", "MTTR", "Environment", "prod", {
                      "label": "Mean Time To Recovery (MTTR)",
                      "stat": "Average"
                    } ]
                  ],
                  "view": "timeSeries",
                  "region": "${AWS::Region}",
                  "title": "Mean Time To Recovery",
                  "period": 300,
                  "yAxis": {
                    "left": {
                      "label": "Minutes"
                    }
                  }
                }
              },
              {
                "type": "metric",
                "width": 12,
                "height": 6,
                "properties": {
                  "metrics": [
                    [ { "expression": "(m2 / m1) * 100", "label": "Change Failure Rate (%)", "id": "e1" } ],
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", { "id": "m1", "visible": false, "stat": "Sum" } ],
                    [ ".", "DeploymentFailures", "Environment", "prod", { "id": "m2", "visible": false, "stat": "Sum" } ]
                  ],
                  "view": "timeSeries",
                  "region": "${AWS::Region}",
                  "title": "Change Failure Rate",
                  "period": 300,
                  "yAxis": {
                    "left": {
                      "label": "Percentage (%)"
                    }
                  }
                }
              },
              {
                "type": "metric",
                "width": 12,
                "height": 6,
                "properties": {
                  "metrics": [
                    [ "${self:service}/DORA", "DeploymentFrequency", "Environment", "prod", {
                      "label": "Deployment Frequency",
                      "stat": "Sum"
                    } ]
                  ],
                  "view": "timeSeries",
                  "region": "${AWS::Region}",
                  "title": "Deployment Frequency",
                  "period": 300,
                  "yAxis": {
                    "left": {
                      "label": "Count"
                    }
                  }
                }
              },
              {
                "type": "metric",
                "width": 12,
                "height": 6,
                "properties": {
                  "metrics": [
                    [ "${self:service}/DORA", "LeadTimeForChanges", "Environment", "prod", {
                      "label": "Lead Time for Changes",
                      "stat": "Average"
                    } ]
                  ],
                  "view": "timeSeries",
                  "region": "${AWS::Region}",
                  "title": "Lead Time for Changes",
                  "period": 300,
                  "yAxis": {
                    "left": {
                      "label": "Minutes"
                    }
                  }
                }
              }
            ]
          }
